# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: 'Junit'
  displayName: 'JunitStage'
  jobs:
    - job: 'Junit Test'
      displayName: 'Running unit tests'
      steps:
        -script: echo 'Running Spring demo app unit test' 
                   Settings
                                             task: Maven@3 
                                                inputs:
                                                    mavenPomFile: 'pom.xml' 
                                                    goals: 'test'
                                                    publishJUnitResults: true
                                                    testResultsFiles: '**/surefire-reports/TEST-*.xml' 
                                                    codeCoverage ToolOption: 'JaCoCo' 
                                                    javaHomeOption: 'JDKVersion' 
                                                    mavenVersionOption: 'Default' 
                                                    mavenAuthenticateFeed: false 
                                                    effectivePomSkip: false 
                                                    sonarQubeRunAnalysis: false 
                                                    checkStyleRunAnalysis: true 
                                                    pmdRunAnalysis: true