# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
  stage: 'Junit'
   displayName: 'Junit Stage'
    jobs:
                      - job: 'Junit Test'
                              displayName: 'Running unit tests'
                              steps:
                                     -script: echo 'Running Spring demo app unit test' 
                                     Settings
                                             task: Maven@3 
                                                inputs:
                                                    mavenPomFile: 'pom.xml' 
                                                    goals: 'test'
                                                    publishJUnitResults: true
                                                    testResultsFiles: '**/surefire-reports/TEST-*.xml' 
                                                    codeCoverage ToolOption: 'JaCoCo' 
                                                    javaHomeOption: 'JDKVersion' 
                                                    mavenVersionOption: 'Default' 
                                                    mavenAuthenticateFeed: false 
                                                    effectivePomSkip: false 
                                                    sonarQubeRunAnalysis: false 
                                                    checkStyleRunAnalysis: true 
                                                    pmdRunAnalysis: true