# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
- stage: 'Junit'
  displayName: 'JunitStage'
  jobs:
    - job: 'JunitTest'
      displayName: 'Running unit tests'
      steps:
        - script: echo 'Running Spring demo app unit test' 
            Settings
        - task: Maven@3 
          inputs:
            mavenPomFile: 'pom.xml' 
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml' 
            codeCoverage ToolOption: 'JaCoCo' 
            javaHomeOption: 'JDKVersion' 
            mavenVersionOption: 'Default' 
            mavenAuthenticateFeed: false 
            effectivePomSkip: false 
            sonarQubeRunAnalysis: false 
            checkStyleRunAnalysis: true 
            pmdRunAnalysis: true
- stage: 'BuildArtifact'
  displayName: Building Artifact' 
  jobs:
   - job: 'BuildArtifact'
     displayName: 'Building Artifact'
     steps:
      - script: echo 'Running Spring demo BuildArtifact' 
          Settings
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          options: '--no-transfer-progress'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false 
          sonarQubeRunAnalysis: false
- actions:
- action: "Build dockerfile"
  type: "DOCKERFILE"
  region: "us-east-1"
  integration_hash: "5ddb7c180fb38be67bd78a88a"
  docker_image_tag: "14.06"
  dockerfile_path: "dir/Dockerfile"
  repository: "MyDockerRepo"
  build_args:
  - "key=value"
  insecure_registry: true
  do_not_prune_images: true
  buildkit: true
  without_progress: true
  secret_id: "secretId"
  secret_src: "path_to_secret"