# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
- stage: 'Junit'
  displayName: 'JunitStage'
  jobs:
    - job: 'JunitTest'
      displayName: 'Running unit tests'
      steps:
        - script: echo 'Running Spring demo app unit test' 
            Settings
        - task: Maven@3 
          inputs:
            mavenPomFile: 'pom.xml' 
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml' 
            codeCoverage ToolOption: 'JaCoCo' 
            javaHomeOption: 'JDKVersion' 
            mavenVersionOption: 'Default' 
            mavenAuthenticateFeed: false 
            effectivePomSkip: false 
            sonarQubeRunAnalysis: false 
            checkStyleRunAnalysis: true 
            pmdRunAnalysis: true
- stage: 'BuildArtifact'
  displayName: Building Artifact' 
  jobs:
   - job: 'BuildArtifact'
     displayName: 'Building Artifact'
     steps:
      - script: echo 'Running Spring demo BuildArtifact' 
          Settings
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          options: '--no-transfer-progress'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false 
          sonarQubeRunAnalysis: false
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: kumarangsk